# **NLP Lecture -04: Text Representation**
- Introduction
- OneHot Encoding
- Bag of Words  --> Mainly used for Text Classification problem
- n-grams
- TF-IDF
- Custom Features
- Assignment

## Assignment_04:
Use the following dataset:- https://www.kaggle.com/lakshmi25npathi/imdb-dataset-of-50k-movie-reviews
- a. Apply all the preprocessing techniques that you think are necessary
- b. Find out the no of words in the entire corpus and also find total no of unique words(vocabulary) using just python
- c. Apply One Hot Encoding
- d. Apply bag of words and find the vocabulary also find the no of times each word has occured
- e. Apply bag of bi-grams and bag of tri-grams and write down your observation about the dimensionality of the vocabulary
- g. Apply tf-idf and find out the idf_scores of words, also find out the vocabulary

# OneHot Encoding
- Corpus: Combination of all strings
- Vocabulary: Unique words of corpus
- Documents: Individual review of data

In [ ]:
# Importing library

import numpy as np 
import pandas as pd

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

In [ ]:
# Creating df
d={'text':['People Watch Utube','Utube Watch Utube','People Write Comments','Utube Write Comments'], 'result':[1,1,0,0]}
df=pd.DataFrame(d)
df

In [ ]:
# Importing Count Vectorizer
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer()

# NOTE: 
# Use binary=True, more useful when doing Sentiment Analysis
# To remove rare words we can use a hyperparameter --> max_feature = n

In [ ]:
# Bag of Words
bow = cv.fit_transform(df['text'])

In [ ]:
# Getting all unique vocabulary
print(cv.vocabulary_)

In [ ]:
# Converting documents into vector
print(bow[0].toarray())
print(bow[1].toarray())
print(bow[2].toarray())
print(bow[3].toarray())

# Note: Check each vocabulary in each documents and create vector

In [ ]:
# For new input
res = cv.transform(['People Watch and Write Comment on Utube']).toarray()
res

# NOTE: Out of Vocabulary problem is get resolved here

# Understanding: sklearn.feature_extraction.text.CountVectorizer

In [ ]:
# Understanding sklearn.feature_extraction.text.CountVectorizer

- Convert a collection of text documents to a matrix of token counts.
CountVectorizer(
    *,
    input='content',
    encoding='utf-8',
    decode_error='strict',
    strip_accents=None,
    lowercase=True,
    preprocessor=None,
    tokenizer=None,
    stop_words=None,
    token_pattern='(?u)\\b\\w\\w+\\b',
    ngram_range=(1, 1),
    analyzer='word',
    max_df=1.0,
    min_df=1,
    max_features=None,
    vocabulary=None,
    binary=False,
    dtype=<class 'numpy.int64'>,)
This implementation produces a sparse representation of the counts using scipy.sparse.csr_matrix.

Parameters
----------
input : {'filename', 'file', 'content'}, default='content'
    - If `'filename'`, the sequence passed as an argument to fit is expected to be a list of filenames that need reading to fetch the raw content to analyze.
    - If `'file'`, the sequence items must have a 'read' method (file-like object) that is called to fetch the bytes in memory.
    - If `'content'`, the input is expected to be a sequence of items that can be of type string or byte.

encoding : str, default='utf-8'
    If bytes or files are given to analyze, this encoding is used to decode.

decode_error : {'strict', 'ignore', 'replace'}, default='strict'
    Instruction on what to do if a byte sequence is given to analyze that contains characters not of the given `encoding`. 
    By default, it is 'strict', meaning that a UnicodeDecodeError will be raised. Other values are 'ignore' and 'replace'.

strip_accents : {'ascii', 'unicode'} or callable, default=None
    Remove accents and perform other character normalization during the preprocessing step.
    'ascii' is a fast method that only works on characters that have a direct ASCII mapping.
    'unicode' is a slightly slower method that works on any characters. None (default) does nothing.
    Both 'ascii' and 'unicode' use NFKD normalization from: func:`unicodedata.normalize`.

lowercase : bool, default=True
    Convert all characters to lowercase before tokenizing.

preprocessor : callable, default=None
    Override the preprocessing (strip_accents and lowercase) stage while preserving the tokenizing and n-grams generation steps.
    Only applies if ``analyzer`` is not callable.

tokenizer : callable, default=None
    Override the string tokenization step while preserving the preprocessing and n-grams generation steps. Only applies if ``analyzer == 'word'``.

stop_words : {'english'}, list, default=None
    If 'english', a built-in stop word list for English is used.
    There are several known issues with 'english' and you should consider an alternative (see :ref:`stop_words`).
    If a list, that list is assumed to contain stop words, all of which will be removed from the resulting tokens. Only applies if ``analyzer == 'word'``.
    If None, no stop words will be used. In this case, setting `max_df`to a higher value, 
    such as in the range (0.7, 1.0), can automatically detect and filter stop words based on intra corpus document frequency of terms.

token_pattern : str or None, default=r"(?u)\\b\\w\\w+\\b"
    Regular expression denoting what constitutes a "token", only used if ``analyzer == 'word'``. 
    The default regexp select tokens of 2 or more alphanumeric characters (punctuation is completely ignored and always treated as a token separator).
    If there is a capturing group in token_pattern then the captured group content, not the entire match, becomes the token. 
    At most one capturing group is permitted.

ngram_range : tuple (min_n, max_n), default=(1, 1)
    The lower and upper boundary of the range of n-values for different word n-grams or char n-grams to be extracted. All values of n such
    such that min_n <= n <= max_n will be used. For example an ``ngram_range`` of ``(1, 1)`` means only unigrams, ``(1, 2)`` means
    unigrams and bigrams, and ``(2, 2)`` means only bigrams. Only applies if ``analyzer`` is not callable.

analyzer : {'word', 'char', 'char_wb'} or callable, default='word'
    Whether the feature should be made of word n-gram or character n-grams.
    Option 'char_wb' creates character n-grams only from text inside word boundaries; n-grams at the edges of words are padded with space.
    If a callable is passed it is used to extract the sequence of features out of the raw, unprocessed input.

    .. versionchanged:: 0.21
    Since v0.21, if ``input`` is ``filename`` or ``file``, the data is first read from the file and then passed to the given callable analyzer.

max_df : float in range [0.0, 1.0] or int, default=1.0
    When building the vocabulary ignore terms that have a document
    frequency strictly higher than the given threshold (corpus-specific stop words).
    If float, the parameter represents a proportion of documents, integer absolute counts.
    This parameter is ignored if vocabulary is not None.

min_df : float in range [0.0, 1.0] or int, default=1
    When building the vocabulary ignore terms that have a document frequency strictly lower than the given threshold. 
    This value is also called cut-off in the literature.
    If float, the parameter represents a proportion of documents, integer absolute counts.
    This parameter is ignored if vocabulary is not None.

max_features : int, default=None
    If not None, build a vocabulary that only consider the top `max_features` ordered by term frequency across the corpus. 
    Otherwise, all features are used. This parameter is ignored if vocabulary is not None.

vocabulary : Mapping or iterable, default=None
    Either a Mapping (e.g., a dict) where keys are terms and values are indices in the feature matrix, or an iterable over terms. 
    If not given, a vocabulary is determined from the input documents. 
    Indices in the mapping should not be repeated and should not have any gap between 0 and the largest index.

binary : bool, default=False
    If True, all non zero counts(like 1,2,3,...) are set to 1. 
    This is useful for discrete probabilistic models that model binary events rather than integer counts.
    
dtype : dtype, default=np.int64
    Type of the matrix returned by fit_transform() or transform().

Attributes
----------
vocabulary_ : dict
    A mapping of terms to feature indices.

fixed_vocabulary_ : bool
    True if a fixed vocabulary of term to indices mapping is provided by the user.

stop_words_ : set
    Terms that were ignored because they either:
      - occurred in too many documents (`max_df`)
      - occurred in too few documents (`min_df`)
      - were cut off by feature selection (`max_features`).
    This is only available if no vocabulary was given.

See Also
--------
HashingVectorizer : Convert a collection of text documents to a matrix of token counts.
TfidfVectorizer : Convert a collection of raw documents to a matrix of TF-IDF features.

Notes
-----
The ``stop_words_`` attribute can get large and increase the model size when pickling. 
This attribute is provided only for introspection and canbe safely removed using delattr or set to None before pickling.

Examples
--------
>>> from sklearn.feature_extraction.text import CountVectorizer
>>> corpus = [
...     'This is the first document.',
...     'This document is the second document.',
...     'And this is the third one.',
...     'Is this the first document?',
... ]
>>> vectorizer = CountVectorizer()
>>> X = vectorizer.fit_transform(corpus)
>>> vectorizer.get_feature_names_out()
array(['and', 'document', 'first', 'is', 'one', 'second', 'the', 'third',
       'this'], ...)
>>> print(X.toarray())
[[0 1 1 1 0 0 1 0 1]
 [0 2 0 1 0 1 1 0 1]
 [1 0 0 1 1 0 1 1 1]
 [0 1 1 1 0 0 1 0 1]]
>>> vectorizer2 = CountVectorizer(analyzer='word', ngram_range=(2, 2))
>>> X2 = vectorizer2.fit_transform(corpus)
>>> vectorizer2.get_feature_names_out()
array(['and this', 'document is', 'first document', 'is the', 'is this',
       'second document', 'the first', 'the second', 'the third', 'third one',
       'this document', 'this is', 'this the'], ...)
 >>> print(X2.toarray())
 [[0 0 1 1 0 0 1 0 0 0 0 1 0]
 [0 1 0 1 0 1 0 1 0 0 1 0 0]
 [1 0 0 1 0 0 0 0 1 1 0 1 0]
 [0 0 1 0 1 0 1 0 0 0 0 0 1]]

# Bag of n-grams
- Here, we consider n-group of words from documents to create a vector

In [ ]:
# Importing Count Vectorizer
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(ngram_range=(2,2))

In [ ]:
# Bag of Words
bow = cv.fit_transform(df['text'])

In [ ]:
# Getting all unique vocabulary
print(cv.vocabulary_)

In [ ]:
# Converting documents into vector
print(bow[0].toarray())
print(bow[1].toarray())
print(bow[2].toarray())
print(bow[3].toarray())

# TF-IDF
- If any word in some particular document is occuring more than other then that word will be given higher weightage compare to other.
- TF: Term Frequency
- IDF: Inverse Document Frequency
- TFIDF = TF*IDF

In [ ]:
# Importing TFIDF-Vectorizer

from sklearn.feature_extraction.text import TfidfVectorizer
tfidf = TfidfVectorizer()

tfidf.fit_transform(df['text']).toarray()  # Why toarray? --> To get sparse matrix in array form

In [ ]:
# Getting IDF value for each term
print(tfidf.idf_)
print(tfidf.get_feature_names_out())

# Custom Features
- No of +ve words
- No of -ve words
- Total no of words
- ...etc